const colors = {
  primary: '#2BBFAA',
  primaryLight: '#E8F8F6',
  primaryDark: '#1A9E8C',
  background: '#F7F9FB',
  white: '#FFFFFF',
  text: '#1A2233',
  textSecondary: '#6B7A99',
  textMuted: '#A0AABF',
  border: '#E8EDF5',
  cardBackground: '#FFFFFF',
  tagBackground: '#E8F8F6',
  tagText: '#2BBFAA',
  danger: '#FF5A65',
  warning: '#FFB74D',
  success: '#4CAF7D',
  shadow: 'rgba(43, 191, 170, 0.10)',
  overlay: 'rgba(26, 34, 51, 0.18)',
  tabBarBackground: '#FFFFFF',
  tabBarActive: '#2BBFAA',
  tabBarInactive: '#A0AABF',
  inputBackground: '#F0F4FA',
  divider: '#EEF1F8',
  progressBar: '#2BBFAA',
  progressBarBackground: '#E8EDF5',
  badgeBackground: '#2BBFAA',
  badgeText: '#FFFFFF',
};

export default colors;
