# Generated by Django 6.0.3 on 2026-04-05 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('comment', 'Comment on your post'), ('like', 'Like on your post'), ('join_request', 'Team join request'), ('join_approved', 'Join request approved'), ('announcement', 'New announcement in your team'), ('project_update', 'Project updated'), ('mention', 'You were mentioned')], max_length=30)),
                ('message', models.CharField(max_length=255)),
                ('target_url', models.CharField(blank=True, default='', max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'tags',
                'ordering': ['-usage_count'],
            },
        ),
    ]
